[coverage:run]

omit =
    qps/pyqtgraph/*


[flake8]

ignore =
    # QGS,
    # D203,
    #  E501 line too long (135 > 120 characters)
    E501,
    # E123 closing bracket does not match indentation of opening bracket's line
    # E123,
    # allow line break before binary operator
    W503,
    # allow continuation line over-indented for hanging indent
    # E126,
    # allow complex functions
    C901,
    # allow unused local variables
    F841,
    #
    QGS201,QGS202
    # QGS401,
    # QGS402,
    # Qt6 / QGIS4 specific
    # QGS403 Enum has been changed in Qt6.
    QGS403,
    # QGS406 QRegExp is removed in Qt6, use QRegularExpression instead
    # QGS406,
    # QGS410 Invalid conversion of QVariant() to NULL. Use from qgis.core import NULL instead.
    # QGS410

max-line-length=120
max-complexity = 10

exclude =
    # No need to traverse our git directory
    .git,
    deploy,
    # There's no value in checking cache directories
    __pycache__,
    # The conf file is mostly autogenerated, ignore it
    docs/source/conf.py,
    deploy,
    qps/pyqtgraph,
    # This contains our built documentation
    build, docs, test-reports, test-outputs, qgisresources
    # skip autogenerated files
    *_rc.py


per-file-ignores =
    #  QGS104 Use 'import qgis.PyQt.pyrcc_main' instead of 'import PyQt5.pyrcc_main'
    # just not available in OSGeo4W installations
    qps/resources.py:QGS104
    # allow QgisInterface as argument
    qps/testing.py:QGS105
    scripts/create_qgisenums.py:QGS102
    # see https://github.com/GispoCoding/flake8-qgis/issues/9
    qps/qgisenums.py:QGS101
    qps/qgisclasses.py:F401
    qps/processing/algorithmdialog.py:QGS105

[pytest]
pythonpath =
   tests/qgispluginsupport

addopts =
    --maxfail=1 -rf
    --ignore=tests/_wip/
    # --cov-config=.coveragec
    # --cov qps
    # --cov qps
norecursedirs =
    .*
    qpstestdata
    qps/pyqtgraph
    scripts
    test-outputs
    *.egg
    venv
    # python_files =
    # tests/layers/test_gdal_metadata.py
    # tests/layers/test_layerconfigwidgets.py
    # tests/layers/layer_properties.py
testpaths =
    tests/

