services:

  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION:-latest}
    tty: true
    working_dir: /usr/src
    volumes:
      - ${GITHUB_WORKSPACE:-.}:/usr/src
