services:

  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_VERSION: ${QGIS_VERSION:-stable}
    tty: true
    working_dir: /usr/src
    volumes:
      - ${GITHUB_WORKSPACE:-.}:/usr/src
