name: ❄ Flake8

on:
  push:
    branches: [master]
    paths:
      - '**.py'
      - '**flake8.yml'

  pull_request:
    branches:
      - '**'
    paths:
      - '**.py'

jobs:
  flake8_py3:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        # uses: actions/setup-python@v2.3.1
        # uses: actions/setup-python@v3.1.3
        uses: actions/setup-python@main
        with:
          python-version: 3.10
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run flake8
        # uses: julianwachholz/flake8-action@v2.0.2
        uses: julianwachholz/flake8-action@main
        with:
          checkName: 'Python Lint'
          plugins: flake8-qgis
          config: .flake8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
