name: 🧪 Tests

on:
  push:
    branches: [master]
    paths:
      - '**.py'

  pull_request:
    branches:
      - '**'
  release:
    types: [published]

jobs:
  # Run unit tests
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        qgis_version: [release-3_28, release-3_30]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        #uses: actions/checkout@v2
        #uses: actions/checkout@v3.50
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Test on QGIS
        run: |
          ls -la .docker/
          chmod +x .docker/run_docker_tests.sh
          chmod +x runtests.sh
          docker-compose -f .docker/docker-compose.gh.yml run qgis ./usr/src/.docker/run_docker_tests.sh

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: ${{ steps.coverage-badge.outputs.coverage-badge }}

      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-badge
          path: coverage-badge

      - name: Update README.md
        run: |
          cp coverage-badge/coverage.svg ./
