name: Linux Tests

on:
  workflow_run:
    workflows: [ "Code Checks" ]
    types: [ completed ]

  push:
    branches:
      # - 'master'
      - '**'
    paths:
      - '**.py'
      - '**.docker/**'

  pull_request:
    branches:
      - master
      - release-**

  release:
    types: [ published ]

jobs:
  # Run unit tests
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
         qgis_version: [ '4.2' ]
    name: QGIS ${{ matrix.qgis_version }}
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Test on QGIS {{matrix.qgis_version}}
        run: |
          ls -la .docker/
          chmod +x run_docker_tests.sh
          chmod +x runtests.sh
          docker compose -f .docker/docker-compose.gh.yml run qgis ./usr/src/run_docker_tests.sh -n auto
